name = "CellMAP"

[folders]
path = [
    "app",
    "src",
    "resource",
    "resource/db0ce7a1-c953-4b15-a71f-ee72ab83c801/.buildtool/25.2.0.2998904/taskTraces",
    "resource/.buildtool/26.2.0.3386108/taskTraces",
    "resource/.buildtool",
    "resource/db0ce7a1-c953-4b15-a71f-ee72ab83c801/.buildtool/25.2.0.2998904",
    "resource/db0ce7a1-c953-4b15-a71f-ee72ab83c801/.buildtool",
    "resource/.buildtool/26.2.0.3386108",
    "resource/db0ce7a1-c953-4b15-a71f-ee72ab83c801",
    "release",
    "release/build",
    "release/package",
]

[[package]]
configuration-name = "CellMAP_AddsOn"
output-file-name = "CellMAP.mltbx"
output-folder = "release"
name = "CellMAPs"
supported-platforms = [
    "windows",
    "linux",
    "macos",
]
display-name = "CellMAP"
version = "1.4.6"
id = "22a12702-d084-4cfb-a6c5-f5e56df80d3b"
use-license-bsd = false
lastAccessed = "1790348140001"
provider.name = "Antoine Allard"
provider.email = "antoine.allard@u-bordeaux.fr"
provider.organization = "Université de Bordaux"
summary = "CellMAP: an open-source software tool to batch-process cell topography and elasticity maps collected by atomic force microscopy."
description = "CellMAP is currently implemented to process AFM maps (*.txt files) and manipulate force curves (*.jpk-qi-data) that have been generated using a Nanowizard AFM (JPK-Bruker) and pre-processed using JPK Data Processing software tool. "
package-root = "/"
product-dependencies = [
    "Curve Fitting Toolbox",
    "Image Processing Toolbox",
    "Statistics and Machine Learning Toolbox",
]
app-gallery-files = [
    "CellMAP.mlapp",
]
preview-image-file = "resource/Icon.png"

[[compiler.standalone]]
configuration-name = "CellMAP_Standalone"
output-folder = "release/build"
installer-output-folder = "release/package"
executable-name = "CellMAP"
suppress-windows-cmd-prompt = true
executable-version = "1.4.2"
installer-version = "1.0.0"
auto-detect-data-files = true
obfuscate-archive = false
verbose = true
embed-archive = true
treat-inputs-as-numeric = false
runtime-delivery = "web"
lastAccessed = "1790346272081"
app-file = "CellMAP.mlapp"
author-email = "antoine.allard@u-bordeaux.fr"
author-company = "Université de Bordeaux"
executable-splash-screen = "resource/Icon.png"
executable-icon = "resource/Icon.png"
author-name = "Antoine Allard"
description = "CellMAP is currently implemented to process AFM maps (*.txt files) and manipulate force curves (*.jpk-qi-data) that have been generated using a Nanowizard AFM (JPK-Bruker) and pre-processed using JPK Data Processing software tool. "
summary = "CellMAP: an open-source software tool to batch-process cell topography and elasticity maps collected by atomic force microscopy."
