function out = LoadingJPK(selpath)
%% This function loads data from JPK
% INPUT:
% selpath: folder to extract data from
% OUTPUT:
% out: struct with data saved under the form:
%   o out.(variable).(cell) where variable can be a Young modulus, indentation, 
%     etc and cell is the name of the cell. This structure contains:
%       * pixel: pixel size
%       * data: matrix of values from variable associated to a cell
%       * unit: unit of the variable (e.g. kPa for Young modulus,...)
%   o out.Force.(cell): contains the folder name where force curves of
%   'cell' are saved.
%   o out.Indentation.(cell): indentation in um for one cell


global iLength

%% First folder to scan is selpath
foldersToEval{1} = selpath;
txtDir = [];
jpkDir = [];
n = 1;
h = waitbar(0.1,'Please wait... CellMAP is reading your data.');

%% Then, scan the folder to look for other folders
while length(foldersToEval) - n >= 0
    InfoDir = dir(fullfile(foldersToEval{n}));
    InfoDirSize = size(InfoDir,1);
    for i = 1:InfoDirSize
        % Find all subfolders to scan
        [~,~,ext] = fileparts(InfoDir(i).name);
        if InfoDir(i).isdir&&~strcmp(InfoDir(i).name,'.')&&~strcmp(InfoDir(i).name,'..')&&~strcmp(InfoDir(i).name,'ForceCurves')
            foldersToEval{end+1} = fullfile(InfoDir(i).folder,InfoDir(i).name); % Add a folder to be scanned
        elseif strcmp(ext,'.txt')
            txtDir = [txtDir;dir(fullfile(InfoDir(i).folder,InfoDir(i).name))]; % Read if there is .txt files to be scanned
        elseif strcmp(ext,'.jpk-qi-data')
            jpkDir = [jpkDir;dir(fullfile(InfoDir(i).folder,InfoDir(i).name))]; % Read if there is .jpk-qi-data files to be scanned
        end
    end
    waitbar(0.2,h,['Number of subfolders scanned: ' num2str(length(foldersToEval)) ...
        ' (' num2str(length(txtDir)) ' .txt and '...
        num2str(length(jpkDir)) ' .jpk-qi-data )']);
    n = n + 1;
end

%% Read and save the data from .txt files generated by JPK
if ~isempty(txtDir)
    % Read .txt files
    waitbar(0,h,'Reading .txt files. Remaining time: Calculating...');
    for txt = 1:length(txtDir)
        tic
        try

            filename = fullfile(txtDir(txt).folder,txtDir(txt).name);
            importedData = importdata(filename,'\t');
            if isstruct(importedData)
                nbHeader = size(importedData.textdata,1);
            else
                nbHeader = 0;
                for j = 1:size(importedData,1)
                    if importedData{j}(1) == '#'
                        nbHeader = nbHeader + 1;
                    end
                end
                importedData = importdata(fullfile(txtDir(txt).folder,txtDir(txt).name),' ',nbHeader);
            end
            j=1;
            importedData_split = cell(1,2);
            for k=1:nbHeader
                temp=strsplit(importedData.textdata{k,1},{'# ',': '},'CollapseDelimiters',true);
                if(size(temp,2)==3)
                    importedData_split{j,1}=temp{1,2};
                    importedData_split{j,2}=temp{1,3};
                    j = j+1;
                end
            end
            nameVar_location = strcmp(importedData_split(:,1),'channel')==1;
            % Remove [number] including brackets and space
            nameVar_tmp = regexprep(importedData_split{nameVar_location,2}, '\[\d+\]\s*', '');
            nameVar = matlab.lang.makeValidName(nameVar_tmp);
            
            nameCell_location = strcmp(importedData_split(:,1),'start date')==1; % Identify the cell to load using the start date as unique Id.
            nameCell = makeRobustDateName(importedData_split{nameCell_location,2});          

            out.(nameVar).(nameCell).data = flip(importedData.data,1);
            out.(nameVar).(nameCell).header = importedData.textdata;

            fastSize_location = find(strcmp(importedData_split(:,1),'fastSize')==1);
            iLength_location = find(strcmp(importedData_split(:,1),'iLength')==1);
            if ~isempty(fastSize_location) || ~isempty(iLength_location)
                fastSize = str2double(importedData_split{fastSize_location,2})*1e6;
                iLength = str2double(importedData_split{iLength_location,2});
                out.(nameVar).(nameCell).pixel = fastSize/iLength;
            else
                out.(nameVar).(nameCell).pixel = 1;
            end
            Unit_location = find(strcmp(importedData_split(:,1),'Unit')==1);
            if ~isempty(Unit_location)
                out.(nameVar).(nameCell).unit =importedData_split{Unit_location,2};
                if strcmp(out.(nameVar).(nameCell).unit,'N')
                    out.(nameVar).(nameCell).unit = 'pN';
                out.(nameVar).(nameCell).data = out.(nameVar).(nameCell).data*1e12;
                elseif strcmp(out.(nameVar).(nameCell).unit,'m')
                    out.(nameVar).(nameCell).unit = 'µm';
                    out.(nameVar).(nameCell).data = out.(nameVar).(nameCell).data*1e6;
                elseif strcmp(out.(nameVar).(nameCell).unit,'Pa')
                    out.(nameVar).(nameCell).unit = 'kPa';
                    out.(nameVar).(nameCell).data = out.(nameVar).(nameCell).data*1e-3;
                end
            else
                out.(nameVar).(nameCell).unit = 'None';
            end
        catch ME
            disp(ME.identifier)
            disp(['Unable to read data from ' txtDir(txt).name])
        end
        t = toc;
        waitbar(txt/length(txtDir),h,{'Reading .txt files.',['Remaining time: ' num2str(round(t*(length(txtDir)-txt)/60)) ' min.']});
    end
end

%% Read and save force curves from JPK
if ~isempty(jpkDir)
    quest = 'There are force curves. Do you want to load them?';
    quest_r = 1;
    while quest_r
        answerUnzip = questdlg(quest,'Read force curves','Estimate total time','Yes','No','Yes');
        switch answerUnzip
            case 'Estimate total time'
                waitbar(0.5,h,{'Reading .jpk-qi-data files.','Calculating... '});
                jpk = 1;
                tic
                ReadJPK(jpkDir(jpk).folder,jpkDir(jpk).name);
                t = toc;
                uiwait(msgbox(['Total time estimate: ' num2str(round(t*length(jpkDir))) ' s.']));
            case 'Yes'
                % Read .jpk-qi-data files
                waitbar(0.1,h,{'Reading .jpk-qi-data files.','Remaining time: Calculating... '});
                for jpk = 1:length(jpkDir)
                    tic
                    zipJavaFile  = java.io.File(fullfile(jpkDir(jpk).folder,jpkDir(jpk).name));
                    % Create a Java ZipFile
                    zipFile = org.apache.tools.zip.ZipFile(zipJavaFile);
                    % Get header.properties
                    dataTmp = getZipFileContent(zipFile,'header.properties');
                    format = repmat('%s',1,100);
                    header_metadata_raw=textscan(dataTmp,format,'whitespace','','delimiter','');
                    header_metadata_raw=header_metadata_raw{1,1};
                    j=1;
                    for i=1:size(header_metadata_raw,1)
                        temp=strsplit(header_metadata_raw{i,1},'=');
                        if(size(temp,2)==2)
                            header_metadata_split{j,1}=temp{1,1};
                            header_metadata_split{j,2}=temp{1,2};
                            j = j+1;
                        end
                    end
                    nameCell_location = strcmp(header_metadata_split(:,1),'quantitative-imaging-map.start-time')==1; % Identify the cell to load using the start date as unique Id.
                    nameCell = makeRobustDateName(header_metadata_split{nameCell_location,2});
                    [indent,height,force] = ReadJPK(jpkDir(jpk).folder,jpkDir(jpk).name);
                    out.Force.(nameCell).force = force;
                    out.Force.(nameCell).height = height;
                    out.Force.(nameCell).indent = indent;
                    out.('Indentation').(nameCell).data = indent;
                    out.('Indentation').(nameCell).unit = 'µm';
                    out.('Indentation').(nameCell).pixel = 1;
        
                    t = toc;
                    waitbar(jpk/length(jpkDir),h,['Reading .jpk-qi-data files. Remaining time: ' num2str(round(t*(length(jpkDir)-jpk))) ' s.']);
                end
                quest_r = 0;
            case 'No'
                for jpk = 1:length(jpkDir)
                    zipJavaFile  = java.io.File(fullfile(jpkDir(jpk).folder,jpkDir(jpk).name));
                    % Create a Java ZipFile
                    zipFile = org.apache.tools.zip.ZipFile(zipJavaFile);
                    % Get header.properties
                    dataTmp = getZipFileContent(zipFile,'header.properties');
                    format = repmat('%s',1,100);
                    header_metadata_raw=textscan(dataTmp,format,'whitespace','','delimiter','');
                    header_metadata_raw=header_metadata_raw{1,1};
                    j=1;
                    for i=1:size(header_metadata_raw,1)
                        temp=strsplit(header_metadata_raw{i,1},'=');
                        if(size(temp,2)==2)
                            header_metadata_split{j,1}=temp{1,1};
                            header_metadata_split{j,2}=temp{1,2};
                            j = j+1;
                        end
                    end
                    nameCell_location = strcmp(header_metadata_split(:,1),'quantitative-imaging-map.start-time')==1; % Identify the cell to load using the start date as unique Id.
                    nameCell = makeRobustDateName(header_metadata_split{nameCell_location,2});  

                    out.Force.(nameCell).jpkDir = jpkDir(jpk);
                    quest_r = 0;
                end
        end
    end
end
close(h);
pause(0.1)
clear h
end